### ISSUE TITLE
Context Panel showing incorrect planets

### ISSUE THREAD

**Issue by doctorspaceman** [WorldWideTelescope/wwt-web-client#115]
Context Menu at bottom showing objects in the FOV isn't working in the web client.  When I move the view to the Center of the milky way (see attached) it shows all planets in the field (which they aren't) and then starts probably showing the images and object (but there is only one slot after the planets on my 1080p monitor).  I think it is just miscalculating which planets to show. See Desktop and Web screenshots at the same location.

Desktop:
![context menu - desktop](https://cloud.githubusercontent.com/assets/9676722/18355965/933cff22-75b0-11e6-85bf-105040b8d1bd.jpg)

Web Client:
![context menu - webclient](https://cloud.githubusercontent.com/assets/9676722/18355974/9c2bf778-75b0-11e6-97f9-4ed2ec3789e4.jpg)

**Comment by thewebkid** [comment]
@astrojonathan I dove into the actual vector values to try to see what was happening, so I picked an arbitrary point in Sagittarius where most of the planets seem to gather in staging :)

http://worldwidetelescope.org/webclient/?debug=1#/ra=18.11738&dec=-30.44950&fov=60.00000

http://wwtstaging.azurewebsites.net/webclient/?debug=1#/ra=18.11738&dec=-30.44950&fov=60.00000

locally I logged the center to corner value to see who is in the viewport and in the constellation:

var ulCoords = args.singleton.getCoordinatesForScreenPoint(0, 0);
var corner = wwtlib.Coordinates.raDecTo3d(ulCoords.x, ulCoords.y);
var center = wwtlib.Coordinates.raDecTo3d($rootScope.viewport.RA, $rootScope.viewport.Dec);
var dist = wwtlib.Vector3d.subtractVectors(corner, center);

in staging dist is around 1.73 at this coordinate
in production, it is 0.86 - about half.

I also logged each of the solar system place distances from center and got
Sun 1.5502826470009272
Mercury 1.5281063221762625
Venus 1.2272889331790184
Mars 0.20721340718480624
Jupiter 1.4280677985645749
Saturn 0.39351505358249433
Uranus 1.6572112077631254
Neptune 1.1303626609506907
Pluto 0.26931992920889536
Moon 0.37835197124914927
Io 1.428352465013534
Europa 1.427932445713827
Ganymede 1.4282157372863948
Callisto 1.4269684203826238

These values are identical in prod. I am giving this one to you since I have evidence that the 3d vector calc is different in the webgl engine :)

**Comment by thewebkid** [comment]
staging now reflects a center to corner vector distance of .87 or 86 during my validations. Closing
