### ISSUE TITLE
Simple animation of overlays doesn't work as expected

### ISSUE THREAD

**Issue by doctorspaceman** [WorldWideTelescope/wwt-web-client#122]
Overlay animations aren’t working as I think they should.  I made a YouTube Video: https://youtu.be/7MQpXEsPn6Y 

If I'm doing something wrong or need to refine documentation let me know.

**Comment by astrojonathan** [comment]
As strange as this sounds. This is working correctly, and the Windows Client works just like this.

What you are doing.
You Created a slide
You created and positioned a ring object and aligned it to the start position.
You clicked the animate on the ring. This made the animate have two keyframes start and end.
While you have the Start selected you moved the sky (this does not automatically sink to the start frame other wise it is a pain to ever change or make an end frame.

While you still had the start selected you moved the ring, since *Overlays* allow live positioning, you were chaning the start position of the overlay. 

Then you clicked set end-position. This set then end positon for the sky, but the overlay already had an end position, and the change you made to the current overlay was to the start postion. The end postion now became the current keyframe, and you saw the ring at the orginal start position captured when you clicked animate.

What you should have done, was select end position for the slide, then adjusted, then clicked Set End Position, and everything would sync correctly.
