### ISSUE TITLE
Ctrl-left click on Mac brings up Finder Scope in addition to rotating view

### ISSUE THREAD

**Issue by patudom** [WorldWideTelescope/wwt-web-client#316]
On a Mac, "right click" can also be done using "ctrl-click."  This means that when a Mac-user rotates the field of view using WWT's ctrl-left-click option, the Finder Scope appears unnecessarily.  It's not really a huge issue, but it is a nuisance.  

If there is a way to sort out the event handlers to prevent this, it would be appreciated. Thanks!

**Comment by pkgw** [comment]
I think that this will be momentarily fixed in the testing version of the webclient. Can you check here:

https://worldwidetelescope.org/testing_webclient/

and see if it seems to be fixed? (If you see this right away, it will take a few minutes for the updated testing version to actually be published.)

**Comment by patudom** [comment]
Yes, this is now behaving sensibly - for both my Mac's trackpad and mouse. Thank you!  

Can we expect the fix to work across all Mac varieties, or should we try to recruit more testers?

**Comment by pkgw** [comment]
I think it ought to work pretty broadly. The tradeoff is that if someone has a one-button mouse, they won't have a way to pop up the Finder Scope ... but I think all Macs are multi-button these days?
